# Quel cadre temporel prendre ?

On s'intéresse à voir si la présence de feux un jour j va impacter la présence d'autres feux autour aux jours j+1,2,3...
L'idée est de déterminer un 'évènement feu', d'un point de vue spatio-temporel. Au niveau de l'espace, on se positionne sur les malles SAFRAN, et on va devoir se reposer (par manque de précision sur les données) sur le lieu de départ du feu, et de l'IFM correspondant à la maille entière. De la même façon, d'un point de vue temporel , nous allons être obligé, par manque de précision sur les données) de nous contenter du jour de début, sans pouvoir vraiment avoir des informations sur la durée et l'étendue du feu. Ce que l'on pourrait regarder néanmoins, c'est l'impact qu'un feu dans une certaine maille pourrait avoir sur l'apparition d'autres feux à proximité (donc soit dans la même maille, soit les mailles à proximité), mais risque

In [2]:
import pandas as pd

In [17]:
df = pd.read_csv('combine.csv', sep=';')
df_landes = df[df['Département'] == '40']
df_landes

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Origine de l'alerte,Moyens de première intervention,Surface parcourue (m2),Surface forêt (m2),...,Décès ou bâtiments touchés,Nombre de décès,Nombre de bâtiments totalement détruits,Nombre de bâtiments partiellement détruits,Hygrométrie (%),Vitesse moyenne du vent (Km/h),Direction du vent,Température (°C),Précision de la donnée,Présence d'un contour valide
652,2006,1876,40,40006,Arengosse,26/07/2006 19:40,Indéterminé,NaN,5000,5000.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
653,2006,1877,40,40151,Lesgor,17/07/2006 15:29,Indéterminé,NaN,66000,60000.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
654,2006,1878,40,40108,Gastes,25/04/2006 18:40,Indéterminé,NaN,400,400.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
655,2006,1879,40,40210,Onesse-et-Laharie,17/07/2006 18:20,Indéterminé,NaN,59000,59000.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
656,2006,1881,40,40167,Luxey,27/07/2006 10:49,Indéterminé,NaN,10,10.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43682,2022,10965,40,40162,Lucbardez-et-Bargues,17/05/2022 20:15,Indéterminé,NaN,8000,8000.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
43683,2022,10967,40,40217,Parentis-en-Born,05/07/2022 16:12,Indéterminé,NaN,118000,8000.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
43684,2022,10968,40,40267,Saint-Justin,03/06/2022 19:14,Indéterminé,NaN,100,100.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
43711,2022,11341,40,40168,Magescq,16/07/2022 16:05,Indéterminé,NaN,28000,28000.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"
43712,2022,11342,40,40296,Seignosse,17/04/2022 01:26,Indéterminé,NaN,10,10.0,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,"

In [18]:
df_landes['Date de première alerte'] = pd.to_datetime(df_landes['Date de première alerte'])

# Extract the date part from the datetime column
df_landes['Date'] = df_landes['Date de première alerte'].dt.date

/tmp/ipykernel_5886/4102152358.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_landes['Date de première alerte'] = pd.to_datetime(df_landes['Date de première alerte'])
/tmp/ipykernel_5886/4102152358.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_landes['Date de première alerte'] = pd.to_datetime(df_landes['Date de première alerte'])
/tmp/ipykernel_5886/4102152358.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_landes['Date'] = df_landes['Date de première alerte'].dt.date

In [20]:
df_landes_chrono = df_landes.sort_values(by='Date')
df_landes_clear = df_landes_chrono[['Date','Code INSEE', 'Nom de la commune']]
df_landes_clear

             Date Code INSEE    Nom de la commune
704    2006-02-14      40149            Lencouacq
813    2006-03-16      40046          Biscarrosse
672    2006-03-25      40230  Pontonx-sur-l'Adour
809    2006-03-27      40019            Aureilhan
727    2006-03-30      40229   Pontenx-les-Forges
...           ...        ...                  ...
43575  2022-10-08      40310             Soustons
43599  2022-10-16      40085           Commensacq
43619  2022-10-20      40142              Laluque
43672  2022-10-26      40142              Laluque
43600  2022-11-01      40267         Saint-Justin

[1680 rows x 3 columns]

In [15]:
df

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Origine de l'alerte,Moyens de première intervention,Surface parcourue (m2),Surface forêt (m2),...,Nombre de décès,Nombre de bâtiments totalement détruits,Nombre de bâtiments partiellement détruits,Hygrométrie (%),Vitesse moyenne du vent (Km/h),Direction du vent,Température (°C),Précision de la donnée,Présence d'un contour valide,Date
0,2006,2,01,01148,Dortan,2006-02-27 13:56:00,Indéterminé,NaN,10000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Données partielles ou non valides,"Non,",2006-02-27
1,2006,3,01,01321,Revonnas,2006-03-15 16:02:00,Indéterminé,NaN,10000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Données partielles ou non valides,"Non,",2006-03-15
2,2006,4,01,01032,Béligneux,2006-03-16 17:03:00,Indéterminé,NaN,10000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Données partielles ou non valides,"Non,",2006-03-16
3,2006,5,01,01109,Collonges,2006-03-27 14:30:00,Indéterminé,NaN,10000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Données partielles ou non valides,"Non,",2006-03-27
4,2006,6,01,01384,Saint-Rambert-en-Bugey,2006-04-24 16:43:00,Indéterminé,NaN,20000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Données partielles ou non valides,"Non,",2006-04-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46140,2022,23340,50,50041,La Hague,2022-07-17 23:55:00,Indéterminé,NaN,60000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,",2022-07-17
46141,2022,23341,50,50616,Le Val-Saint-Père,2022-07-24 16:51:00,Indéterminé,NaN,20000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,",2022-07-24
46142,2022,23343,50,50066,Jullouville,2022-07-26 20:25:00,Indéterminé,NaN,20000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,",2022-07-26
46143,2022,23345,50,50570,Savigny-le-Vieux,2022-08-05 14:39:00,Indéterminé,NaN,35000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,",2022-08-05
46144,2022,23351,50,50447,Saint-Aubin-des-Préaux,2022-08-12 15:35:00,Indéterminé,NaN,6000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non,",2022-08-12